version: '3.8'

services:  
  
  postgresql:
    image: postgres:14
    hostname: postgresql
    volumes:
      - tkx_pg_data:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "change_me"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor-console:
    image: conduktor/conduktor-console:1.22.0
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    volumes:
      - tkx_conduktor_data:/var/conduktor
    environment:
      CDK_DATABASE_URL: "postgresql://conduktor:change_me@postgresql:5432/conduktor-console"
      CDK_CLUSTERS_0_ID: "orchestrate-nonprod"
      CDK_CLUSTERS_0_NAME: "orchestrate-nonprod"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "b-1.tkx-nonprod-kafka.vcxyxv.c4.kafka.ap-southeast-1.amazonaws.com:9092,b-2.tkx-nonprod-kafka.vcxyxv.c4.kafka.ap-southeast-1.amazonaws.com:9092,b-3.tkx-nonprod-kafka.vcxyxv.c4.kafka.ap-southeast-1.amazonaws.com:9092"
      # CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "b-1.tkxsandboxalphaka.wjj3hw.c3.kafka.ap-southeast-1.amazonaws.com:9092,b-2.tkxsandboxalphaka.wjj3hw.c3.kafka.ap-southeast-1.amazonaws.com:9092,b-3.tkxsandboxalphaka.wjj3hw.c3.kafka.ap-southeast-1.amazonaws.com:9092"
      # CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "redpanda-0:9092"
      # CDK_CLUSTERS_0_SCHEMAREGISTRY_URL: "http://redpanda-0:18081
      CDK_CLUSTERS_0_COLOR: "#6A57C8"
      CDK_CLUSTERS_0_ICON: "kafka"
      CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
      CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
      CDK_MONITORING_CALLBACK-URL: http://conduktor-console:8080/monitoring/api/
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:8080

  conduktor-monitoring:
    image: conduktor/conduktor-console-cortex:1.22.0
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8080"
 
volumes:
  tkx_pg_data: {}
  tkx_conduktor_data: {}
